server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root        # 🔁 change if you use another user
    password: admin    # 🔁 set your MySQL password

  jpa:
    hibernate:
      ddl-auto: update   # Flyway manages schema; use "update" for quick dev
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

#  flyway:
#    enabled: false
#    locations: classpath:db/migration
#    url: jdbc:mysql://localhost:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    user: root
#    password: admin

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.springframework.jdbc.core: INFO
    org.hibernate.SQL: INFO
