apiVersion: batch/v1
kind: Job
metadata:
  name: init-topics
  namespace: oms
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: bitnami/kafka:3.7
          command: ["bash","-lc"]
          args:
            - |
              set -e
              echo "Waiting for Kafka..."
              for i in {1..60}; do
                /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1 && break
                sleep 2
              done
              echo "Creating topics..."
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --topic order.created        --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --topic payment.authorized   --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --topic payment.captured     --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --topic payment.failed       --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --topic inventory.reserved   --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --topic inventory.failed     --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --topic notification.send    --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3
              echo "Done."
