apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: oms
spec:
  selector: { app: notification-service }
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      nodePort: 30084
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: oms
spec:
  replicas: 1
  selector: { matchLabels: { app: notification-service } }
  template:
    metadata: { labels: { app: notification-service } }
    spec:
      containers:
        - name: app
          image: onlinebooking-notification-service
          ports: [ { containerPort: 8084 } ]
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          livenessProbe:
            tcpSocket: { port: 8084 }
            initialDelaySeconds: 25
          readinessProbe:
            tcpSocket: { port: 8084 }
            initialDelaySeconds: 15
