apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: oms
spec:
  selector: { app: order-service }
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30088
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: oms
spec:
  replicas: 1
  selector: { matchLabels: { app: order-service } }
  template:
    metadata: { labels: { app: order-service } }
    spec:
      containers:
        - name: app
          image: onlinebooking-order-service
          ports: [ { containerPort: 8081 } ]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          livenessProbe:
            tcpSocket: { port: 8081 }
            initialDelaySeconds: 25
          readinessProbe:
            tcpSocket: { port: 8081 }
            initialDelaySeconds: 15
